// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfnqmdmsapovxdjwdhsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbnFtZG1zYXBvdnhkandkaHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTIwMDgsImV4cCI6MjA2MTg2ODAwOH0.COLWed6k7Mw7kAevxuJtZtJv_Z0YTu4p9GN1NBTH_kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);